### ISSUE TITLE
Translate all french texts in gm commands

### ISSUE THREAD

**Issue by kelno** [Nqsty/Sunstrider-Issues#31]
In contrary to scripts, maybe we can keep those hardcoded, we don't really care for french texts for gm's

**Comment by kelno** [comment]
The following files are concerned :
src/game/Level1.cpp
src/game/Level2.cpp
src/game/Level3.cpp
src/game/Debugcmds.cpp

**Comment by kelno** [comment]
Done in Level0 by Leekie here : 
Nqsty/sunstrider@03ae9742fb1c6f458bbe54e5e7017b59b6167a52

**Comment by Nqsty** [comment]
Level3 done here :
https://github.com/Nqsty/sunstrider/commit/ecab268f2f05e19aa67a6aef82729fc6470ec872
